In [21]:
import pandas as pd
import json
import re
import csv
 
# A regex converted that filters out entries that are not in city, State format
# we need this later on to extract long and lat for each location
def regex_getter(entry):
    
    txt = entry

    re1='((?:[a-z][a-z]+))'	# Word 1
    re2='(,)'	# Any Single Character 1
    re3='(\\s+)'	# White Space 1
    re4='((?:(?:AL)|(?:AK)|(?:AS)|(?:AZ)|(?:AR)|(?:CA)|(?:CO)|(?:CT)|(?:DE)|(?:DC)|(?:FM)|(?:FL)|(?:GA)|(?:GU)|(?:HI)|(?:ID)|(?:IL)|(?:IN)|(?:IA)|(?:KS)|(?:KY)|(?:LA)|(?:ME)|(?:MH)|(?:MD)|(?:MA)|(?:MI)|(?:MN)|(?:MS)|(?:MO)|(?:MT)|(?:NE)|(?:NV)|(?:NH)|(?:NJ)|(?:NM)|(?:NY)|(?:NC)|(?:ND)|(?:MP)|(?:OH)|(?:OK)|(?:OR)|(?:PW)|(?:PA)|(?:PR)|(?:RI)|(?:SC)|(?:SD)|(?:TN)|(?:TX)|(?:UT)|(?:VT)|(?:VI)|(?:VA)|(?:WA)|(?:WV)|(?:WI)|(?:WY)))(?![a-z])'	# US State 1

    rg = re.compile(re1+re2+re3+re4,re.IGNORECASE|re.DOTALL)
    m = rg.search(txt)
    if m:
        word1=m.group(1)
        c1=m.group(2)
        ws1=m.group(3)
        usstate1=m.group(4)
        return str((word1 +  c1 +ws1 + usstate1))



# import json package to load json file
#with open('bernie_raw_tweets.json',encoding="utf8") as jsonFile:
with open('donald_raw_tweets.json',encoding="utf8") as jsonFile:
    polls_json = json.loads('[{}]'.format(jsonFile.read()))

# Get the coulmns user and location from the data frame and extract 
tweets_list = [(dct['user']['location'], dct["text"]) for dct in polls_json]
colNames = ("location", "text")
tweets_df = pd.DataFrame(tweets_list, columns=colNames)


tweets_df=tweets_df.dropna()

tweets_df.head()

df = pd.DataFrame([])

#gets and prints the split of city and state
for i in tweets_df.ix[:,0]:
    if regex_getter(i) != None:
        city,state = regex_getter(i).split(',')
        #print(city,state)

        
#open a csv and write cities and states 
with open("city_states.csv", "w", newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['City', 'State','Color'])
    for i in tweets_df.ix[:,0]:
        if regex_getter(i) != None:
            data = regex_getter(i).split(',')
            #blue or red for GOP or Democratic
            data.append('red')
            #strip white spaces from column 2
            data[1] = data[1].strip()
            print(data)
            writer.writerow(data)

['Huron', 'MI', 'red']
['Roswell', 'NM', 'red']
['Raton', 'FL', 'red']
['Phoenix', 'AZ', 'red']
['Clearwater', 'FL', 'red']
['Collierville', 'TN', 'red']
['Nashville', 'TN', 'red']
['Miami', 'FL', 'red']
['Jacksonville', 'NC', 'red']
['Tampa', 'FL', 'red']
['Nashville', 'TN', 'red']
['City', 'FL', 'red']
['Hartford', 'CT', 'red']
['Charlotte', 'NC', 'red']
['Nashville', 'TN', 'red']
['Orleans', 'LA', 'red']
['Worth', 'TX', 'red']
['Lewiston', 'ME', 'red']
['Atlanta', 'GA', 'red']
['Salem', 'MO', 'red']
['Atlanta', 'GA', 'red']
['boston', 'ma', 'red']
['Saybrook', 'CT', 'red']
['Brooklyn', 'NY', 'red']
['Nashville', 'TN', 'red']
['Angeles', 'CA', 'red']
['Pumpkintown', 'SC', 'red']
['Donna', 'TX', 'red']
['Pleasantville', 'NY', 'red']
['Benton', 'AR', 'red']
['Charleston', 'SC', 'red']
['Atlanta', 'GA', 'red']
['Francisco', 'CA', 'red']
['Indio', 'CA', 'red']
['Louis', 'MO', 'red']
['Vegas', 'NV', 'red']
['Cities', 'MN', 'red']
['Monterey', 'CA', 'red']
['Clarita', 'CA', 'red']
['Clarita', 'CA', 'red']
['Mobile', 'AL', 'red']
['Bentonville', 'AR', 'red']
['Clarita', 'CA', 'red']
['Diego', 'CA', 'red']
['Vegas', 'NV', 'red']
['Clarita', 'CA', 'red']
['Linda', 'CA', 'red']
['Redan', 'GA', 'red']
['Cleveland', 'OH', 'red']
['Elgin', 'Il', 'red']
['York', 'NY', 'red']
['Francisco', 'CA', 'red']
['Camarillo', 'CA', 'red']
['Marcos', 'TX', 'red']
['Diego', 'CA', 'red']
['Charlotte', 'NC', 'red']
['Diego', 'CA', 'red']
['Fresno', 'CA', 'red']
['Riverside', 'Ca', 'red']
['Foley', 'AL', 'red']
['Raleigh', 'NC', 'red']
['Nashville', 'TN', 'red']
['Boston', 'MA', 'red']
['Shorewood', 'IL', 'red']
['Newport', 'SC', 'red']
['Charlotte', 'NC', 'red']
['Scottsdale', 'AZ', 'red']
['Honesdale', 'PA', 'red']
['Greenville', 'SC', 'red']
['Leandro', 'CA', 'red']
['Katy', 'TX', 'red']
['Branch', 'MS', 'red']
['Lansing', 'MI', 'red']
['Savannah', 'GA', 'red']
['Bronx', 'NY', 'red']
['Louisville', 'KY', 'red']
['Chicago', 'IL', 'red']
['Washington', 'DC', 'red']
['Nashville', 'TN', 'red']
['Tallulah', 'La', 'red']
['Raton', 'FL', 'red']
['Coamo', 'PR', 'red']
['Hattiesburg', 'MS', 'red']
['Toledo', 'OH', 'red']
['York', 'NY', 'red']
['Valley', 'CA', 'red']
['Hills', 'CA', 'red']
['Atlanta', 'GA', 'red']
['McKinney', 'TX', 'red']
['Bay', 'FL', 'red']
['Reno', 'NV', 'red']
['Austin', 'TX', 'red']
['Bronx', 'NY', 'red']
['Chicago', 'IL', 'red']
['Beach', 'FL', 'red']
['Beach', 'CA', 'red']
['Bay', 'FL', 'red']
['York', 'NY', 'red']
['Charlotte', 'NC', 'red']
['Beach', 'CA', 'red']
['Palestine', 'IN', 'red']
['Atlanta', 'GA', 'red']
['Carson', 'CA', 'red']
['York', 'NY', 'red']
['Tampa', 'FL', 'red']
['Savannah', 'GA', 'red']
['Boston', 'MA', 'red']
['Centereach', 'NY', 'red']
['Bayshore', 'NC', 'red']
['Francisco', 'CA', 'red']
['Riverside', 'Ca', 'red']
['Boston', 'MA', 'red']
['Prestonsburg', 'Ky', 'red']
['Elgin', 'Il', 'red']
['Medina', 'OH', 'red']
['Centereach', 'NY', 'red']
['Bronx', 'NY', 'red']
['Lansing', 'MI', 'red']
['Atlanta', 'GA', 'red']
['Riverside', 'CA', 'red']
['Phoenix', 'AZ', 'red']
['Barbara', 'CA', 'red']
['Lancaster', 'CA', 'red']
['Superior', 'WI', 'red']
['BROOKLYN', 'NY', 'red']
['Worth', 'TX', 'red']
['Park', 'MD', 'red']
['Tamarac', 'FL', 'red']
['Washington', 'DC', 'red']
['Lincoln', 'NE', 'red']
['Shorewood', 'IL', 'red']
['City', 'TN', 'red']
['Miami', 'FL', 'red']
['Barbara', 'CA', 'red']
['Charlotte', 'NC', 'red']
['Shorewood', 'IL', 'red']
['Glen', 'NY', 'red']
['Diego', 'CA', 'red']
['Manhattan', 'NY', 'red']
['Springs', 'NY', 'red']
['York', 'NY', 'red']
['Diego', 'CA', 'red']
['Manhattan', 'NY', 'red']
['Lincoln', 'NE', 'red']
['Lansing', 'MI', 'red']
['Beach', 'FL', 'red']
['Raton', 'FL', 'red']
['Township', 'MI', 'red']
['Orlando', 'FL', 'red']
['York', 'NY', 'red']
['Island', 'NY', 'red']
['City', 'UT', 'red']
['Diego', 'CA', 'red']
['Angeles', 'CA', 'red']
['Nashville', 'TN', 'red']
['York', 'NY', 'red']
['Seattle', 'WA', 'red']
['Angeles', 'CA', 'red']
['Angeles', 'CA', 'red']
['Nashville', 'TN', 'red']
['Bentonville', 'AR', 'red']
['Plano', 'TX', 'red']
['Lexington', 'KY', 'red']
['Angeles', 'CA', 'red']
['Charlotte', 'NC', 'red']
['Riverside', 'CA', 'red']
['Bedford', 'MA', 'red']
['Nashville', 'TN', 'red']
['Decatur', 'GA', 'red']
['Palmdale', 'CA', 'red']
['Cucamonga', 'CA', 'red']
['Nashville', 'TN', 'red']
['Atlanta', 'GA', 'red']
['Boston', 'MA', 'red']
['Nagu', 'PR', 'red']
['Charlotte', 'NC', 'red']
['Francisco', 'CA', 'red']
['Mohave', 'AZ', 'red']
['Miami', 'FL', 'red']
['Atlanta', 'GA', 'red']
['Francisco', 'CA', 'red']
['Fitzgerald', 'GA', 'red']
['Osgood', 'IN', 'red']
['Nashville', 'TN', 'red']
['Edinburg', 'TX', 'red']
['Nashville', 'TN', 'red']
['Charlotte', 'NC', 'red']
['Nashville', 'TN', 'red']
['Boston', 'MA', 'red']
['York', 'NY', 'red']
['Orleans', 'LA', 'red']
['Centereach', 'NY', 'red']
['Nashville', 'TN', 'red']
['Phoenix', 'AZ', 'red']
['Boston', 'MA', 'red']
['Nashville', 'TN', 'red']
['Mills', 'NC', 'red']
['Boston', 'MA', 'red']
['Angeles', 'CA', 'red']
['Plano', 'TX', 'red']
['Bethlehem', 'PA', 'red']

In [23]:
df_1= pd.read_csv('locations1.csv')

df_2 = pd.read_csv('city_states.csv')

print(df_1)
print(df_2)
    
df = pd.merge(df_1, df_2, left_on=['state','city'], right_on=['State','City'])

      state          city        lat         lng
0        AL         Acmar  33.584132  -86.515570
1        AL    Adamsville  33.588437  -86.959727
2        AL         Adger  33.434277  -87.167455
3        AL      Keystone  33.236868  -86.812861
4        AL      New Site  32.941445  -85.951086
5        AL        Alpine  33.331165  -86.208934
6        AL          Arab  34.328339  -86.489638
7        AL     Baileyton  34.268298  -86.621299
8        AL      Bessemer  33.409002  -86.947547
9        AL      Hueytown  33.414625  -86.999607
10       AL  Blountsville  34.092937  -86.568628
11       AL        Bremen  33.973664  -87.004281
12       AL         Brent  32.935670  -87.211387
13       AL    Brierfield  33.042747  -86.951672
14       AL        Calera  33.109800  -86.755987
15       AL   Centreville  32.950324  -87.119240
16       AL       Chelsea  33.371582  -86.614132
17       AL   Coosa Pines  33.266928  -86.337622
18       AL       Clanton  32.835532  -86.642472
19       AL     Cleveland  33.992106  -86.559355
20       AL    Columbiana  33.176964  -86.616145
21       AL    Crane Hill  34.082117  -87.048395
22       AL      Cropwell  33.506448  -86.280026
23       AL       Cullman  34.176146  -86.829777
24       AL      Dolomite  33.465424  -86.956435
25       AL          Dora  33.734947  -87.040148
26       AL        Empire  33.825589  -87.016139
27       AL     Fairfield  33.473494  -86.918262
28       AL      Coalburg  33.611283  -86.813614
29       AL    Gardendale  33.718910  -86.822481
...     ...           ...        ...         ...
25788    WY    Ranchester  44.768228 -107.303429
25789    WY  Rock Springs  41.605957 -109.230047
25790    WY     Bondurant  43.223798 -110.335287
25791    WY       Boulder  42.688146 -109.540105
25792    WY          Cora  43.139921 -109.915351
25793    WY      Evanston  41.260947 -110.963067
25794    WY  Fort Bridger  41.282820 -110.347428
25795    WY   Green River  41.519590 -109.471445
25796    WY      Lonetree  41.049144 -110.172862
25797    WY         Lyman  41.329136 -110.292629
25798    WY     Mc Kinnon  41.040898 -109.874536
25799    WY      Pinedale  42.854331 -109.856088
25800    WY    Colter Bay  43.460734 -110.766277
25801    WY         Kelly  43.609361 -110.544186
25802    WY         Moose  43.771201 -110.857493
25803    WY         Moran  43.881635 -110.329429
25804    WY        Wilson  43.499220 -110.874199
25805    WY      Kemmerer  41.788661 -110.528340
25806    WY         Afton  42.712829 -110.941976
25807    WY        Auburn  42.805114 -110.994415
25808    WY       Bedford  42.932336 -110.955560
25809    WY     Marbleton  42.552059 -110.132954
25810    WY     Cokeville  42.057983 -110.916419
25811    WY        Daniel  42.917629 -110.133624
25812    WY          Etna  43.138606 -111.015996
25813    WY       Freedom  43.017167 -111.029178
25814    WY        Grover  42.796472 -110.924392
25815    WY      La Barge  42.247340 -110.210865
25816    WY         Smoot  42.619238 -110.922351
25817    WY        Thayne  42.933026 -111.011354

[25818 rows x 4 columns]
              City State Color
0            Huron    MI   red
1          Roswell    NM   red
2            Raton    FL   red
3          Phoenix    AZ   red
4       Clearwater    FL   red
5     Collierville    TN   red
6        Nashville    TN   red
7            Miami    FL   red
8     Jacksonville    NC   red
9            Tampa    FL   red
10       Nashville    TN   red
11            City    FL   red
12        Hartford    CT   red
13       Charlotte    NC   red
14       Nashville    TN   red
15         Orleans    LA   red
16           Worth    TX   red
17        Lewiston    ME   red
18         Atlanta    GA   red
19           Salem    MO   red
20         Atlanta    GA   red
21          boston    ma   red
22        Saybrook    CT   red
23        Brooklyn    NY   red
24       Nashville    TN   red
25         Angeles    CA   red
26     Pumpkintown    SC   red
27           Donna    TX   red
28   Pleasantville    NY   red
29          Benton    AR   red
..             ...   ...   ...
171      Nashville    TN   red
172        Atlanta    GA   red
173         Boston    MA   red
174           Nagu    PR   red
175      Charlotte    NC   red
176      Francisco    CA   red
177         Mohave    AZ   red
178          Miami    FL   red
179        Atlanta    GA   red
180      Francisco    CA   red
181     Fitzgerald    GA   red
182         Osgood    IN   red
183      Nashville    TN   red
184       Edinburg    TX   red
185      Nashville    TN   red
186      Charlotte    NC   red
187      Nashville    TN   red
188         Boston    MA   red
189           York    NY   red
190        Orleans    LA   red
191     Centereach    NY   red
192      Nashville    TN   red
193        Phoenix    AZ   red
194         Boston    MA   red
195      Nashville    TN   red
196          Mills    NC   red
197         Boston    MA   red
198        Angeles    CA   red
199          Plano    TX   red
200      Bethlehem    PA   red

[201 rows x 3 columns]

In [24]:
#df[['lng','lat','Color']].to_csv('bernie.txt', sep='\t', header=False, index=False)
df[['lng','lat','Color']].to_csv('donald.txt', sep='\t', header=False, index=False)

In [1]:

print(df[['lng','lat','Color']])

NameError: name 'df' is not defined